### ISSUE TITLE
Revisit licensing issues

### ISSUE THREAD

**Issue by frangio** [spalladino/solidity-docgen#1]
The solidity-antlr4 grammar is licensed [under GPL](https://github.com/solidityj/solidity-antlr4/blob/master/LICENSE). This may not enable solidity-docgen to be MIT licensed as it is now.

We'd need to look into it and see if the licensing is compatible, and otherwise change the project to GPL or reach out to @federicobond who offered to help work it out (https://github.com/OpenZeppelin/zeppelin-solidity/issues/594#issuecomment-355876659).

**Comment by spalladino** [comment]
We are now using the solc compiler directly. Closing this issue.
